### PR TITLE
Bookstore: Using Redux in React components

### PR DESCRIPTION
**Pull request by learnwithalfred**
## The following requirements has been completed

-  First of all - make sure that you keep state immutable in reducers ✔️ 
 - Import Redux Provider and your store in the main component of your React app ✔️ 
 - Connect your app to the Redux store.✔️ 
 -  Make sure that list of books displays books from Redux store. ✔️ 
 -  In your React component responsible for adding new books, add functionality for "Add new" button ✔️ 
 - Remove button implemented ✔️ 

### Video description

https://user-images.githubusercontent.com/34389326/178336922-bb3d4b88-575f-4e69-a6b4-3db3f422eb85.mov

### CODE REVIEW

**Comment by learnwithalfred** [comment]
Please this review is for the  Bookstore: Using Redux in React components only

it was mistakenly submitted to the API request one and i cannot undo it

Please if possible do not review it against the `Bookstore: connect to API task`

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Invalid Code Review Request ❌

Hi @learnwithalfred, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, for review Bookstore: Connect to API but have completed the milestone for Bookstore: Use Redux in React Components. Kindly make sure to submit for correct review request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by learnwithalfred** [comment]
Please It was a reiew for the  Bookstore: Using Redux in React components  project

But whiles submitting it i mistakenly submitted it against the wrong day.
But on the dashboard it said you have already claim it so i cannot undo the submission

**Review by Mre55 — CHANGES_REQUESTED** [review]
**Hi @learnwithalfred,**

You have done a great job so far! 💪 👏 
You still need to work on a few issues before moving on to the next project, but you're almost there!

## To highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 

## Required Changes ♻️🛠️ 

- [ ] Kindly, implement a dispatch action for `category page` for `Check Status` button which have to dispatch and show a text which can be initial state with text of `Under Construction`.
image


_Check the comments under the review._




## Optional suggestions 🟡 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by sja-thedude — APPROVED** [review]
## Project Approved 👍 

Hi @learnwithalfred, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

giphy

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
